apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: claw

resources:
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/openclaw/openclaw
    newName: ghcr.io/openclaw/openclaw
    newTag: 2026.5.7-slim
