apiVersion: claw.sandbox.redhat.com/v1alpha1
kind: Claw
metadata:
  name: openshell-instance
spec:
  credentials:
    - name: openai
      type: bearer
      secretRef:
        - name: openai-api-key
          key: api-key
      provider: openai
  openshell:
    enabled: true
    gatewayRef:
      name: openshell
      namespace: openshell-alice
    openClawImage: quay.io/sallyom/openclaw:openshell
    sandboxImage: quay.io/sallyom/openclaw-openshell-sandbox:latest
    mode: remote
