apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: claw-device-pairing

resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
